apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: employees
spec:
  containers:
    - name: webapp
      image: <your_ecr_url>/webapp:latest
      ports:
        - containerPort: 8080
