apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 626108377158.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pass@1234
            - name: MYSQL_DATABASE
              value: employees
          ports:
            - containerPort: 3306
              name: mysql
          readinessProbe:
            exec:
              command:
              - mysqladmin
              - ping
              - -h
              - localhost
              - -u
              - root
              - -ppass@1234
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
              - mysqladmin
              - ping
              - -h
              - localhost
              - -u
              - root
              - -ppass@1234
            initialDelaySeconds: 60
            periodSeconds: 30
      imagePullSecrets:
        - name: regcred