apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: web
  labels:
    app: employees
spec:
  containers:
  - name: web-app
    image: 626108377158.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
    env:
    - name: DBHOST
      value: mysql-service.db.svc.cluster.local
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: root
    - name: DBPWD
      value: pass@1234
    - name: DATABASE
      value: employees
    - name: APP_COLOR
      value: lime
    ports:
    - containerPort: 8080
      name: http
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
  imagePullSecrets:
    - name: regcred