apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: employees
spec:
  containers:
    - name: webapp
      image: 626108377158.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
      ports:
        - containerPort: 8080
