apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: webapp
          image: 626108377158.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
          env:
            - name: DBHOST
              value: mysql
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: root
            - name: DBPWD
              value: password
            - name: DATABASE
              value: employees
            - name: APP_COLOR
              value: blue
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: employees
spec:
  type: NodePort
  selector:
    app: employees
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
